import type { Metadata } from "next";
import { Geist, TASA_Orbiter } from "next/font/google";
import "./globals.css";

const tasaOrbiter = TASA_Orbiter({
  variable: "--font-tasa",
  subsets: ["latin"],
  weight: ["500", "600", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${tasaOrbiter.variable} antialiased`} lang="pl">
      <body>{children}</body>
    </html>
  );
}
