import type { Metadata } from "next";
import {
  Instrument_Serif,
  Playfair_Display,
  TASA_Orbiter,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import QueryClientProviderWrapper from "@/app/providers/QueryClientProviderWrapper";
import { FilterMobileWrapper } from "@/app/trasy/components/FilterMobileWrapper";
import Header from "@/app/components/header/Header";
import { Footer } from "@/app/components/footer/Footer";
import MobileHeader from "@/app/components/header/MobileHeader";

const tasaOrbiter = TASA_Orbiter({
  variable: "--font-tasa",
  subsets: ["latin"],
  weight: ["500", "600", "400", "700", "800"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-tasa",
  subsets: ["latin"],
  weight: ["500", "600", "400", "700", "800"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${tasaOrbiter.variable} ${playfairDisplay.variable} ${instrumentSerif.variable}  antialiased`}
      lang="pl"
    >
      <body className="relative scroll-smooth">
        <FilterMobileWrapper />
        <Header />
        <MobileHeader />
        <QueryClientProviderWrapper>{children}</QueryClientProviderWrapper>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
